chore/change-images-to-cloudinary
marcioflaviof/rd2-homepage pull request #2
Opened 2022-09-27 19:26 UTC by marcioflaviof

2022-09-27 20:52 UTC, erickcelio requested changes

2022-09-27 20:52 UTC, erickcelio commented on package.json
> +    "@cloudinary/url-gen": "^1.8.6",
Essas 2 deps são necessárias ? :thinking:

2022-09-27 20:52 UTC, erickcelio commented on src/pages/index.tsx
> +            src="/rd2/mobile/homepage/main_banner_ujmyeo.jpg"
Esqueci de comentar, mas em todas as imagens tu pode remover a extensão, que o cloudinary vai saber se ele vai retornar um webp ou um png se o browser não suportar

2022-09-27 20:52 UTC, erickcelio commented on src/pages/index.tsx
>            <Image
Ah tem uma feature q é interessante pra esse caso do banner, como é tipo a principal imagem e tal o next-image tem uma prop [loading](https://nextjs.org/docs/api-reference/next/image#loading) que ela pode fazer o eager loading da imagem, nesse caso acho legal usarmos aqui, e tbm quando testei na vercel um problema que vi foi quando abrimos o menu, o fundo do menu é uma imagem certo, ai é legal esse fundo ter o eager pro modal n se perder no side igual tá rolando.

2022-09-27 22:22 UTC, marcioflaviof commented on package.json
> +    "@cloudinary/url-gen": "^1.8.6",
Acredito que não, acabei instalando enquanto tentava fazer funcionar :sweat_smile:

2022-10-11 19:55 UTC, erickcelio approved these changes

2022-10-11 20:42 UTC, merged